"""Add kana column and missing fields to candidates

Revision ID: 6ebdeed2a97a
Revises: 0dcb87e9ada4
Create Date: 2025-12-15 16:40:52.939944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebdeed2a97a'
down_revision: Union[str, Sequence[str], None] = '0dcb87e9ada4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('kana', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidates', sa.Column('token_issued_at', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('token_sent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('interviews', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('interviews', sa.Column('current_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('interviews', sa.Column('reverse_qa_logs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'reverse_qa_logs')
    op.drop_column('interviews', 'current_stage')
    op.drop_column('interviews', 'retry_count')
    op.drop_column('candidates', 'token_sent_type')
    op.drop_column('candidates', 'token_issued_at')
    op.drop_column('candidates', 'kana')
    # ### end Alembic commands ###
